global using NetPackageAnalyzerConsole;
global using System.Diagnostics;
global using System.Text.Json;
//global using NS_;
global using OutDated = NS_GeneratedJson_outdatedV1_gen_json;
global using Deprecated = NS_GeneratedJson_deprecatedV1_gen_json;
global using All = NS_GeneratedJson_includeV1_gen_json;
global using static System.Console;
global using NetPackageAnalyzerConsole.generatedPartial;
global using NS_GeneratedJson_deprecatedV1_gen_json;
global using NetPackageAnalyzerWork;
global using System.CommandLine;
global using AnalyzeMerge;
global using System.IO.Abstractions;
