global using NetPackageAnalyzerConsole;
global using System.Diagnostics;
global using System.Text.Json;
//global using NS_;
global using static System.Console;
global using System.CommandLine;
global using AnalyzeMerge;
global using System.IO.Abstractions;
global using NetPackageAnalyzerDocusaurus;
global using NetPackageAnalyzerObjects;
global using WhatIAmDoingData;
global using NetPackageAnalyzerShowInConsole;
global using RSCG_InterceptMethodCommon;